fixed missing parameter

diff --git a/templates/deployment.yaml b/templates/deployment.yaml
--- a/templates/deployment.yaml
+++ b/templates/deployment.yaml
@@ -179,7 +179,7 @@ spec:
           
           {{- if and (.Values.serial.ip) (.Values.serial.port) (not .Values.nocheckconn) }}
           echo "checking connection to {{ .Values.serial.ip }}:{{ .Values.serial.port }}"
-          socat TCP:{{ .Values.serial.ip }}:{{ .Values.serial.port }},connect-timeout=2 || (echo "## failed to connect to {{ .Values.serial.ip }}:{{ .Values.serial.port }} " && exit 1)
+          socat /dev/null TCP:{{ .Values.serial.ip }}:{{ .Values.serial.port }},connect-timeout=2 || (echo "## failed to connect to {{ .Values.serial.ip }}:{{ .Values.serial.port }} " && exit 1)
           echo "connection to {{ .Values.serial.ip }}:{{ .Values.serial.port }} successful"
           {{- end }}
           ## if also in devices if defined for server/ip and port
