sleep 2 to release connection

diff --git a/templates/deployment.yaml b/templates/deployment.yaml
--- a/templates/deployment.yaml
+++ b/templates/deployment.yaml
@@ -187,7 +187,7 @@ spec:
             {{- range .Values.devices }}
               {{- if and (.server) (.port) (not .nocheckconn) }}
           echo "checking connection to {{ .server }}:{{ .port }} ..."
-          socat -T1 /dev/null TCP:{{ .server }}:{{ .port }} || (echo "## failed to connect to {{ .server }}:{{ .port }} " && exit 1)
+          socat /dev/null TCP:{{ .server }}:{{ .port }} || (echo "## failed to connect to {{ .server }}:{{ .port }} " && exit 1)
           echo "connection to {{ .server }}:{{ .port }} successful!!"
           sleep 2
               {{- end }}
